{% set name = "molsimplify" %}
{% set version = "1.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hjkgrp/molSimplify/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6f3ae62bd3cec844b886afc929253e45c471d67614d4f9ed2eddca984eaf2eb5
  patches:
    - pyproject.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - openbabel
    - numpy
    - scikit-learn
    - pandas
    - keras
    - scipy
    - pyyaml
    - tensorflow
    - hyperopt
    - pre-commit

test:
  imports:
    - molSimplify
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://molsimplify.mit.edu
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A toolkit for automating discovery in inorganic chemistry
  description: |
    molSimplify is an open source toolkit for the automated, 
    first-principles screening and discovery of new inorganic molecules
    and intermolecular complexes. 
  doc_url: https://molsimplify.readthedocs.io/
  dev_url: https://github.com/hjkgrp/molSimplify

extra:
  recipe-maintainers:
    - jan-janssen
