{% set name = "molsimplify" %}
{% set version = "1.5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hjkgrp/molSimplify/archive/refs/heads/master.tar.gz
  sha256: afeb6a843b66ee9a4f8efc878dffd5fa84cc618cfe1c9fffc04a725f7ba753f2
  patches:
    - openbabel.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - openbabel
    - numpy 
    - scikit-learn
    - pandas 
    - keras
    - scipy
    - pyyaml
    - tensorflow
    - hyperopt

test:
  imports:
    - molSimplify
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://molsimplify.mit.edu
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'A toolkit for automating discovery in inorganic chemistry'
  description: |
    molSimplify is an open source toolkit for the automated, 
    first-principles screening and discovery of new inorganic molecules
    and intermolecular complexes. 
  doc_url: https://molsimplify.readthedocs.io/
  dev_url: https://github.com/hjkgrp/molSimplify

extra:
  recipe-maintainers:
    - jan-janssen
