schema_version: 1

context:
  name: molsimplify
  version: "2.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/hjkgrp/molSimplify/archive/refs/tags/v${{ version }}.tar.gz
  sha256: b8d0a58b87c9650a1d3b620421a5360d27ddd6dcef7a974aa71bfdf628e5f8c2
  patches:
    - pyproject.patch

build:
  number: 0
  skip: 
    - win
    - match(python, "<3.13")
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
    - setuptools
  run:
    - python
    - openbabel
    - numpy
    - scikit-learn
    - pandas
    - keras
    - scipy
    - pyyaml
    - tensorflow
    - hyperopt
    - pre-commit
    - importlib-resources
    - pydentate
    - matplotlib-base

tests:
  - python:
      imports:
        - molSimplify
      pip_check: true

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: A toolkit for automating discovery in inorganic chemistry
  description: |
    molSimplify is an open source toolkit for the automated,
    first-principles screening and discovery of new inorganic molecules
    and intermolecular complexes.
  homepage: https://molsimplify.mit.edu
  repository: https://github.com/hjkgrp/molSimplify
  documentation: https://molsimplify.readthedocs.io/

extra:
  recipe-maintainers:
    - jan-janssen
